//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telephone_Directory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DirectoryModelContainer : DbContext
    {
        public DirectoryModelContainer()
            : base("name=DirectoryModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SubscribersInfo> SubscribersInfoSet { get; set; }
        public virtual DbSet<ConnectionsInfo> ConnectionsInfoSet { get; set; }
        public virtual DbSet<OperatorsInfo> OperatorsInfoSet { get; set; }
        public virtual DbSet<UsersInfo> UsersInfoSet { get; set; }
    }
}
